T3MVCProjectSolution/T3MVCProject/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using T3MVCProject.Models;
using T3MVCProject.Services;

namespace T3MVCProject.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            this._orderService = orderService;
        }
        public IActionResult Index()
        {
            return View(_orderService.GetAllOrder());
        }

        public IActionResult Details(int id)
        {
            Order order = _orderService.GetOrderById(id);

            dynamic orderViewModel = new ExpandoObject();
            orderViewModel.Orders = order;
            orderViewModel.OrderItems = _orderService.GetAllOrderItem().Where(o => o.OrderId == order.OrderId);

            return View(orderViewModel);
        }
        //public IActionResult Edit(int id)
        //{
        //    Order order = _repo.Get(id);
        //    return View(order);
        //}

        //[HttpPost]
        //public IActionResult Edit(int id, Order order)
        //{
        //    _repo.Update(order);
        //    return RedirectToAction("Index");
        //}

        //public IActionResult Create()
        //{
        //    return View(new Order());
        //}

        //[HttpPost]
        //public IActionResult Create(Order order)
        //{
        //    _repo.Add(order);
        //    return RedirectToAction("Index");
        //}

        //public IActionResult Delete(int id)
        //{
        //    Order order = _repo.Get(id);
        //    return View(order);
        //}
        //[HttpPost]
        //public IActionResult Delete(int id, Order order)
        //{
        //    _repo.Remove(id);
        //    return RedirectToAction("Index");
        //}
    }
}

T3MVCProjectSolution/T3MVCProject/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using T3MVCProject.Models;
using T3MVCProject.Services;
using System.Diagnostics;

namespace T3MVCProject.Controllers
{
    public class UserController : Controller
    {
        private readonly IRepo<string, User> _adding;
        private readonly IRepo<int, Shopper> _repo;
        private readonly LoginService _loginService;

        public UserController(IRepo<string, User> adding,
                                IRepo<int, Shopper> repo,
                               LoginService lservice)
        {
            _adding = adding;
            _repo = repo;
            _loginService = lservice;
        }


        public IActionResult Register()
        {
            ViewBag.Roles = GetUserRoles();
            ViewBag.Genders = GetGenders();
            return View(new UserShopper());
        }




        [HttpPost]
        public IActionResult Register(UserShopper userShopper)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    User user = new User();
                    Shopper shopper = new Shopper();
                    shopper = _repo.Add(shopper);

                    
                    user.ShopperId = shopper.ShopperId;
                    user.Username = userShopper.Username;
                    user.Password = userShopper.Password;
                    user.Email = userShopper.Email;
                    user.Phone = userShopper.Phone;
                    user.Role = userShopper.Role;
                    user.Address = userShopper.Address;
                    user.DOB = userShopper.DOB;
                    user.Gender = userShopper.Gender;

                    _adding.Add(user);

                    TempData.Add("un", user.Username);
                    
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(userShopper, ex.Message);
                }

            }
            return RedirectToAction("Login");
        }



        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Login(User user)
        {
            var myuser = _loginService.LoginCheck(user);
            if (myuser == null)
                return View();
            HttpContext.Session.SetString("un", user.Username);


            return RedirectToAction("Index", "Home");
        }


        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }




        //Initialize user roles
        IEnumerable<SelectListItem> GetUserRoles()
        {
            List<SelectListItem> roles = new List<SelectListItem>();
            roles.Add(new SelectListItem { Text = "Admin", Value = "admin" });
            roles.Add(new SelectListItem { Text = "Shopper", Value = "shopper" });
            return roles;
        }

        //Initialize genders
        IEnumerable<SelectListItem> GetGenders()
        {
            List<SelectListItem> genders = new List<SelectListItem>();
            genders.Add(new SelectListItem { Text = "Male", Value = "male" });
            genders.Add(new SelectListItem { Text = "Female", Value = "female" });
            return genders;
        }
    }
}

T3MVCProjectSolution/T3MVCProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - T3MVCProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/T3MVCProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">T3MVCProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Order List</a>
                        </li>
                    </ul>

                    <partial name="_NavAuthentication.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - T3MVCProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

T3MVCProjectSolution/T3MVCProject/Views/Shared/_NavAuthentication.cshtml
@if (@ViewBag.Username == null)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="User" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    @*<a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="User" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>*@
}
else
{

    @*
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>

            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }
        </ul>
    </div>*@
    <span style="padding: 5px;"></span>
    <form asp-controller="User" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
    }